server:
  port: 8888

elasticjob:
  enable: true
  addSchedule: true
  regCenter:
    namespace: xsy_job_space
    serverList: 127.0.0.1:2181

spring:
  datasource:
    druid:
      es-job:
        url: jdbc:mysql://127.0.0.1:3306/xsy_job?serverTimezone=Asia/Shanghai&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&useAffectedRows=true&socketTimeout=30000
        username: root
        password: root

mybatis:
  mapper-locations: 'classpath*:mappers/**/*.xml'
  mapper-scan: 'com.xsy'
